---

- name: upload images to public_registry from outside
  hosts: outside
  gather_facts: no
  vars_files:
    - host_vars/images.yml
  tasks:
  - name: Install Docker Service
    become: yes
    apt: name=docker.io update_cache=yes

  - name: Create docker override config file
    become: yes
    template:
      src: "daemon.json.j2"
      dest: /etc/docker/daemon.json
    notify: restart docker
    when: public_registry is defined and public_registry and not is_secure_public_registry

  - name: install python-pip
    become: yes
    apt: name={{ item }}
    with_items:
      - python-pip
  
  - name: Upgrade pip
    pip:
      name: pip
      extra_args: --upgrade

  - name: Install Docker-py
    pip: name=docker-py

  - name: Tag and push to public registry
    docker_image:
      name: "{{item}}"
      repository: "{{ public_registry }}/{{ item | regex_replace('(docker.io|quay.io|k8s.gcr.io|gcr.io)/') }}"
      push: yes
      source: pull
    with_items: "{{ images }}"
  
  handlers:
  - name: restart docker
    become: yes
    service: name=docker state=restarted
    listen: restart docker
  